spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://dpg-d51sirjuibrs739halcg-a.frankfurt-postgres.render.com:5432/dbmealy?sslmode=require
spring.datasource.username=adminmealy
spring.datasource.password=aQIQ2cDrlKaXyoWSB7qYI8ZW5p1h3Odm
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
server.port=${PORT:8080}